# Generated by go2rpm 1
%bcond_without check

# https://github.com/lestrrat-go/jwx
%global goipath         github.com/lestrrat-go/jwx
Version:                0.9.0

%gometa

%global common_description %{expand:
Implementation of various JWx technologies.}

%global golicenses      LICENSE
%global godocs          README.md jwt/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Implementation of various JWx technologies

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/pkg/errors)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md jwt/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sat Jan 25 22:40:52 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0.9.0-1
- Initial package
